/**
 * Экспорт данных каталога в JSON для служебных скриптов
 * (проверка источников, генерация sitemap, импорт, дифф и отчёты).
 *
 * Скрипты инфраструктуры написаны на JS, а данные — на TypeScript: этот модуль
 * собирается esbuild и печатает снимок каталога в stdout.
 */
import {
  MODELS,
  TRIMS,
  PRICES,
  OFFERS,
  STOCK_ITEMS,
  CREDIT_PROGRAMS,
  OFFICIAL_SPECS,
  MODEL_EQUIPMENT,
  GENERATIONS,
  SOURCE_DOCUMENTS,
  PRICE_CHANGES,
  CATALOG_CHANGES,
  OFFICIAL_PRICE_COUNT,
  CATALOG_FIXED_AT,
  lastSuccessfulCheck,
  minCurrentPrice,
  trimsForModel,
} from '../src/data/haval'

const payload = {
  catalogFixedAt: CATALOG_FIXED_AT,
  lastSuccessfulCheck: lastSuccessfulCheck(),
  officialPriceCount: OFFICIAL_PRICE_COUNT,
  trimsTotal: TRIMS.length,
  trimsCurrent: TRIMS.filter((t) => t.status === 'current').length,
  models: MODELS.map((m) => {
    const min = minCurrentPrice(m.id)
    return {
      id: m.id,
      slug: m.slug,
      name: m.name,
      family: m.family,
      bodyType: m.bodyType,
      priceListUrl: m.priceListUrl,
      catalogueUrl: m.catalogueUrl,
      officialUrl: m.officialUrl,
      sourceUrl: m.sourceUrl,
      image: m.image,
      officialImages: m.officialImages,
      availability: m.availability,
      trims: trimsForModel(m.id).length,
      priceFrom: min?.basePrice ?? null,
    }
  }),
  trims: TRIMS.map((t) => ({
    id: t.id,
    modelId: t.modelId,
    name: t.name,
    modelYear: t.modelYear,
    productionYear: t.productionYear,
    engine: t.engine,
    horsepower: t.horsepower,
    transmission: t.transmission,
    drivetrain: t.drivetrain,
    basePrice: t.basePrice,
    priceType: t.priceType ?? 'msrp',
    status: t.status,
    priceSourceUrl: t.priceSourceUrl,
    priceValidFrom: t.priceValidFrom,
    priceUpdatedAt: t.priceUpdatedAt,
    equipment: t.equipment,
    specifications: t.specifications,
  })),
  prices: PRICES.map((p) => ({
    id: p.id,
    trimId: p.trimId,
    modelId: p.modelId,
    amount: p.amount,
    priceType: p.priceType,
    modelYear: p.modelYear,
    productionYear: p.productionYear,
    status: p.status,
    conditions: p.conditions,
    sourceUrl: p.sourceUrl,
    effectiveFrom: p.effectiveFrom,
    verifiedAt: p.verifiedAt,
  })),
  offers: OFFERS.map((o) => ({
    id: o.id,
    name: o.name,
    modelIds: o.modelIds,
    trimIds: o.trimIds ?? [],
    modelYears: o.modelYears ?? [],
    offerType: o.offerType,
    discountAmount: o.discountAmount,
    discountPercent: o.discountPercent,
    finalPrice: o.finalPrice,
    validFrom: o.validFrom,
    validUntil: o.validUntil,
    sourceUrl: o.sourceUrl,
    status: o.status,
  })),
  programs: CREDIT_PROGRAMS.map((p) => ({
    id: p.id,
    name: p.name,
    modelIds: p.modelIds,
    termMonthsMin: p.termMonthsMin,
    termMonthsMax: p.termMonthsMax,
    downPaymentMinPct: p.downPaymentMinPct,
    downPaymentMaxPct: p.downPaymentMaxPct,
    baseRate: p.baseRate,
    sourceUrl: p.sourceUrl,
    validFrom: p.validFrom,
    validUntil: p.validUntil,
  })),
  stock: STOCK_ITEMS.map((s) => ({
    id: s.id,
    modelId: s.modelId,
    trimId: s.trimId,
    trimName: s.trimName,
    price: s.price,
    priceType: s.priceType,
    productionYear: s.productionYear,
    color: s.color,
    vehicleId: s.vehicleId,
    region: s.region,
    dealer: s.dealer,
    status: s.status,
    sourceUrl: s.sourceUrl,
    verifiedAt: s.verifiedAt,
  })),
  specs: OFFICIAL_SPECS.map((s) => ({
    modelId: s.modelId,
    sourceUrl: s.sourceUrl,
    verifiedAt: s.verifiedAt,
    modelYears: s.modelYears,
    bodyType: s.bodyType,
    seats: s.seats,
    unknownFields: s.unknownFields,
  })),
  equipment: MODEL_EQUIPMENT.map((e) => ({
    modelId: e.modelId,
    sourceUrl: e.sourceUrl,
    verifiedAt: e.verifiedAt,
    standardItems: e.standard.reduce((n, g) => n + g.items.length, 0),
    matrixRows: e.matrix.length,
  })),
  generations: GENERATIONS,
  sourceDocuments: SOURCE_DOCUMENTS,
  priceChanges: PRICE_CHANGES,
  catalogChanges: CATALOG_CHANGES,
}

process.stdout.write(JSON.stringify(payload, null, 2))
